# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
    slack(message: "App successfully tested!", slack_url: ENV["SLACK_URL"])
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
    slack(
      message: "App successfully released in Beta",
      success: true,
      slack_url: ENV["SLACK_URL"]
    )
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Run Slack test for automate release"
  lane :slack_message do
  slack(
    message: "Slack successfully tested",
    success: true,
    slack_url: ENV["SLACK_URL"]
  )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    increment_version_code(gradle_file_path: "app/build.gradle")
    gradle(
      task: "clean assembleRelease", 
      build_type: "release",
      properties: {
        "android.injected.signing.store.password" => ENV["KEYSTORE_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["KEY_ALIAS"],
        "android.injected.signing.key.password" =>  ENV["KEY_PASSWORD"]
      }
    )
    upload_to_play_store
    slack(
      message: "App successfully uploaded to the PlayStore",
      success: true,
      slack_url: ENV["SLACK_URL"]
  )
  end
end
